---
MainSourceFile:  '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
Diagnostics:
  - DiagnosticName:  modernize-avoid-c-arrays
    DiagnosticMessage:
      Message:         'do not declare C-style arrays, use ''std::array'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
      FileOffset:      92
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-avoid-c-arrays
    DiagnosticMessage:
      Message:         'do not declare C-style arrays, use ''std::array'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
      FileOffset:      134
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-avoid-c-arrays
    DiagnosticMessage:
      Message:         'do not declare C-style arrays, use ''std::array'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
      FileOffset:      150
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-trailing-return-type
    DiagnosticMessage:
      Message:         use a trailing return type for this function
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
      FileOffset:      178
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
          Offset:          174
          Length:          3
          ReplacementText: auto
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
          Offset:          184
          Length:          0
          ReplacementText: ' -> int'
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-bool-literals
    DiagnosticMessage:
      Message:         converting integer literal to bool, use bool literal instead
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
      FileOffset:      217
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
          Offset:          217
          Length:          1
          ReplacementText: 'false'
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-nullptr
    DiagnosticMessage:
      Message:         use nullptr
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
      FileOffset:      233
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/llama/gen_2/00002_2/0166_602_C._The_Two_Routes.cpp'
          Offset:          233
          Length:          1
          ReplacementText: nullptr
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
...
