---
MainSourceFile:  '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
Diagnostics:
  - DiagnosticName:  modernize-use-trailing-return-type
    DiagnosticMessage:
      Message:         use a trailing return type for this function
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
      FileOffset:      95
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          91
          Length:          3
          ReplacementText: auto
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          156
          Length:          0
          ReplacementText: ' -> int'
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-emplace
    DiagnosticMessage:
      Message:         use emplace instead of push
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
      FileOffset:      294
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          294
          Length:          6
          ReplacementText: 'emplace('
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          308
          Length:          1
          ReplacementText: ''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-emplace
    DiagnosticMessage:
      Message:         use emplace instead of push
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
      FileOffset:      656
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          656
          Length:          6
          ReplacementText: 'emplace('
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          672
          Length:          1
          ReplacementText: ''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-trailing-return-type
    DiagnosticMessage:
      Message:         use a trailing return type for this function
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
      FileOffset:      758
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          754
          Length:          3
          ReplacementText: auto
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          764
          Length:          0
          ReplacementText: ' -> int'
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  modernize-use-nullptr
    DiagnosticMessage:
      Message:         use nullptr
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
      FileOffset:      811
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/qwen/gen_1/00002/0165_602_C._The_Two_Routes.cpp'
          Offset:          811
          Length:          1
          ReplacementText: nullptr
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
...
