---
MainSourceFile:  '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
Diagnostics:
  - DiagnosticName:  modernize-use-trailing-return-type
    DiagnosticMessage:
      Message:         use a trailing return type for this function
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      103
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          99
          Length:          3
          ReplacementText: auto
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          109
          Length:          0
          ReplacementText: ' -> int'
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      1431
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          1431
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      2270
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          2270
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      2348
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          2348
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      2426
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          2426
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      2909
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          2909
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      2992
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          2992
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      3081
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          3081
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
  - DiagnosticName:  performance-avoid-endl
    DiagnosticMessage:
      Message:         'do not use ''endl'' with streams; use ''\n'' instead'
      FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
      FileOffset:      3162
      Replacements:
        - FilePath:        '/home/saif/Documents/aigc_vul_patterns/derived/cpp/gemma/gen_1/00002/0143_602_C._The_Two_Routes.cpp'
          Offset:          3162
          Length:          4
          ReplacementText: '''\n'''
    Level:           Warning
    BuildDirectory:  '/home/saif/Documents/aigc_vul_patterns'
...
